### ISSUE TITLE
install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)

### ISSUE THREAD

**Issue by libin1993** [hongyangAndroid/FitAndroid7#1]
app更新时，已经授予了读写权限，但是加上install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)这句后，android7.0就会报Permission Denial，提示没有授权；我去掉install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)，app能够安装，但是安装完成后的页面直接闪退，不能提示用户打开app,请问这是什么原因呢；

@Override
    public void onReceive(Context context, Intent intent) {
        if (intent.getAction().equals(DownloadManager.ACTION_DOWNLOAD_COMPLETE)) {
            Intent install = new Intent(Intent.ACTION_VIEW);
            //判断是否是AndroidN以及更高的版本
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                Uri contentUri = FileProvider.getUriForFile(context, "cn.cloudworkshop.miaoding.fileprovider", file);
                //授予读写权限
                install.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
//                List<ResolveInfo> resInfoList = context.getPackageManager()
//                        .queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
//                for (ResolveInfo resolveInfo : resInfoList) {
//                    String packageName = resolveInfo.activityInfo.packageName;
//                    context.grantUriPermission(packageName, contentUri,
//                            Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
//                }

                install.setDataAndType(contentUri, "application/vnd.android.package-archive");
            } else {
                install.setDataAndType(Uri.fromFile(file), "application/vnd.android.package-archive");

            }
            install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(install);
        }
    }

**Comment by hongyangAndroid** [comment]
你好，我拿7.0测试了下：

```
public void installApk(View view) {
        // 需要自己修改安装包路径
        File file = new File(Environment.getExternalStorageDirectory(),
                "app-debug.apk");
        Intent intent = new Intent(Intent.ACTION_VIEW);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        FileProvider7.setIntentDataAndType(this,
                intent, "application/vnd.android.package-archive", file, true);
        startActivity(intent);
    }
```

>注：存储权限需要手动打开，可以关注下后台日志。

不管是否设置newtask，安装都正常； 安装后apk也能够正常打开。

可否提供更详细的信息？

**Comment by libin1993** [comment]
/**
     * 下载文件
     */
    private void downloadFile(String url) {
        DownloadManager manager = (DownloadManager) getSystemService(Context.DOWNLOAD_SERVICE);
        DownloadManager.Request request = new DownloadManager.Request(Uri.parse(url));

        request.setTitle("妙定");
        request.setDescription("正在下载");
        // 设置下载可见
        request.setVisibleInDownloadsUi(true);
        //下载完成后通知栏可见
        request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);
        //当前网络状态
        ConnectivityManager mConnectivityManager = (ConnectivityManager)
                getSystemService(Context.CONNECTIVITY_SERVICE);
        NetworkInfo networkInfo = mConnectivityManager.getActiveNetworkInfo();
        if (networkInfo != null && networkInfo.isConnected()) {
            String type = networkInfo.getTypeName();
            if (type.equalsIgnoreCase("MOBILE")) {
                request.setAllowedNetworkTypes(DownloadManager.Request.NETWORK_MOBILE);
            }
        }
        // 设置下载位置
        File file = new File(Environment.getExternalStorageDirectory().getAbsolutePath(),
                "CloudWorkshop/miaoding.apk");
        request.setDestinationUri(Uri.fromFile(file));

        service = new DownloadService(file);
        registerReceiver(service, new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE));
        manager.enqueue(request);
    }

public class DownloadService extends BroadcastReceiver {

    private File file;

    public DownloadService(File file) {
        this.file = file;
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        if (intent.getAction().equals(DownloadManager.ACTION_DOWNLOAD_COMPLETE)) {
            Intent install = new Intent(Intent.ACTION_VIEW);
            Uri contentUri;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                install.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
                contentUri = FileProvider.getUriForFile(context, "cn.cloudworkshop.miaoding.fileprovider", file);

                List<ResolveInfo> resInfoList = context.getPackageManager().queryIntentActivities(intent,  PackageManager.MATCH_DEFAULT_ONLY);
                for (ResolveInfo resolveInfo : resInfoList) {
                    String packageName = resolveInfo.activityInfo.packageName;
                    context.grantUriPermission(packageName, contentUri,  Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
                }
            } else {
                contentUri = Uri.fromFile(file);

            }
            install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            install.setDataAndType(contentUri, "application/vnd.android.package-archive");
            context.startActivity(install);
        }
    }
}


这是我的完整代码，实在不知道错在哪儿了，只知道小米6 android7.1中加了install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)，就会报这个java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord；把这句代码注释掉就能安装，只是安装结束后没有安装成功页面，看着像是闪退一样，还得去桌面手动打开app

**Comment by libin1993** [comment]
```
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="cn.cloudworkshop.miaoding.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"
                tools:replace="android:resource"/>
</provider>

<paths>
    <root-path name="root" path="" />
    <external-path name="external" path="" />
</paths>
```

**Comment by hongyangAndroid** [comment]
```
install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
```
这行代码放到你addFlags前面试试~~

我这还没有小米6~~拿的nexus测试的~

**Comment by libin1993** [comment]
```
public class DownloadService extends BroadcastReceiver {

    private File file;

    public DownloadService(File file) {
        this.file = file;
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        if (intent.getAction().equals(DownloadManager.ACTION_DOWNLOAD_COMPLETE)) {
            Intent install = new Intent(Intent.ACTION_VIEW);
            install.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            Uri contentUri;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                install.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
                contentUri = FileProvider.getUriForFile(context, "cn.cloudworkshop.miaoding.fileprovider", file);

                List<ResolveInfo> resInfoList = context.getPackageManager().queryIntentActivities(intent,  PackageManager.MATCH_DEFAULT_ONLY);
                for (ResolveInfo resolveInfo : resInfoList) {
                    String packageName = resolveInfo.activityInfo.packageName;
                    context.grantUriPermission(packageName, contentUri,  Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
                }
            } else {
                contentUri = Uri.fromFile(file);
            }
            install.setDataAndType(contentUri, "application/vnd.android.package-archive");
            context.startActivity(install);
        }
    }
}
```

放在前面就好了，这是什么鬼啊，谢谢啊

**Comment by hongyangAndroid** [comment]
ok~

**Comment by bitterking** [comment]
牛逼！放到后面确实不行

**Comment by bitterking** [comment]
setflags 放后面就把前面addflags给覆盖掉了，加的权限就废了，被摧残了一下午~~~

**Comment by zhoujunyou** [comment]
也遇到了这个问题 也被摧残了一下午 感谢🙏
