### ISSUE TITLE
裁剪遇到的问题

### ISSUE THREAD

**Issue by Blizzard-liu** [hongyangAndroid/FitAndroid7#2]
intent.putExtra(MediaStore.EXTRA_OUTPUT, desUri);   /////是file:/// 不报错 ,改成content://反而报错

java.lang.SecurityException: Permission Denial: writing android.support.v4.content.FileProvider uri content://com.galaxyschool.app.wawaschool.fileprovider/external/lqwawa/wawatong/icon/zoom_icon.jpg from pid=20723, uid=10071 requires the provider be exported, or grantUriPermission()
请问 是啥原因呢 

 /**
     * @param activity    当前activity
     * @param orgUri      剪裁原图的Uri /////7.0必须是content://
     * @param desUri      剪裁后的图片的Uri /////必须是file:///
     * @param aspectX     X方向的比例
     * @param aspectY     Y方向的比例
     * @param width       剪裁图片的宽度
     * @param height      剪裁图片高度
     * @param requestCode 剪裁图片的请求码
     */
    public static void startZoomPhoto(Activity activity, File orgUri, File desUri, int aspectX, int aspectY, int width, int height, int requestCode) {
        doCrop(activity, FileProviderHelper.getUriForFile(activity,orgUri),FileProviderHelper.getUriForFile(activity,desUri),
                 aspectX, aspectY, width, height, requestCode);
    }

    private static void doCrop(Activity activity, Uri orgUri, Uri desUri, int aspectX, int aspectY, int width, int height, int requestCode) {
        Intent intent = new Intent("com.android.camera.action.CROP");
        FileProviderHelper.setIntentDataAndType(activity,
                intent, "image/*", orgUri, true); /////7.0必须是content://
        intent.putExtra("crop", "true");
        intent.putExtra("aspectX", aspectX);
        intent.putExtra("aspectY", aspectY);
        intent.putExtra("outputX", width);
        intent.putExtra("outputY", height);
        intent.putExtra("scale", true);
        //将剪切的图片保存到目标Uri中
        intent.putExtra(MediaStore.EXTRA_OUTPUT, desUri);   /////是file:/// 不报错 ,改成content://反而报错
        intent.putExtra("return-data", false);
        intent.putExtra("outputFormat", Bitmap.CompressFormat.JPEG.toString());
        intent.putExtra("noFaceDetection", true);

        activity.startActivityForResult(intent, requestCode);
    }

**Comment by Blizzard-liu** [comment]
打开裁剪界面的时候不报错  点击裁剪完成的时候才报错

**Comment by Blizzard-liu** [comment]
百思不得其姐

**Comment by hongyangAndroid** [comment]
use:
```
FileProvider7.setIntentDataAndType();
FileProvider7.grantPermissions();
```

**Comment by Blizzard-liu** [comment]
我查了资料发现输出的uri    就是用Uri.formFille()这个方法才行 ,

intent.putExtra(MediaStore.EXTRA_OUTPUT, desUri)/////是file:/// 不报错 ,改成content://反而报错

**Comment by hongyangAndroid** [comment]
看来crop这块，orgUri需要使用content://，而destUri则还保持file://。

**Comment by Blizzard-liu** [comment]
是的  困扰了好久

**Comment by hongyangAndroid** [comment]
thx ~ 稍后我也更新下readme提醒下~

**Comment by liukefu2050** [comment]
请问这个问题怎么解决的，我也碰到这个问题，我使用的是Ucrop
改成////是file:/// 不报错，怎么兼容7.0呢
